<?php

namespace Drupal\ckeditor_support\Form;

use Drupal\Core\Form\FormStateInterface;
use Drupal\entity_embed\Form\EntityEmbedDialog as BaseEntityEmbedDialog;

class EntityEmbedDialog extends BaseEntityEmbedDialog {
  //@todo : Store data in MediaImageDecorator
  //@todo : Replace view_mode by custom formatter in entity-embed-display
  //@todo : Create custom entity_embed_display to reproduce media_image_display formatter work
  //@todo : Pray
  public function buildEmbedStep(array $form, FormStateInterface $form_state) {
    $form = parent::buildEmbedStep($form, $form_state); // TODO: Change the autogenerated stub
    $entity_element = $form_state->get('entity_element');
    $image_styles = image_style_options(FALSE);
    $form['attributes']['data-entity-embed-image-style'] = [
      '#title' => t('Image style'),
      '#type' => 'select',
      '#default_value' => $entity_element['data-entity-embed-display'],
      '#empty_option' => t('None (original image)'),
      '#options' => $image_styles,
    ];
    return $form;
  }


}
